AWSTemplateFormatVersion: '2010-09-09'
Description: A demo S3 bucket notification system.
Parameters:
  BucketName:
    Description: S3 Bucket name
    Type: String
    Default: item-purchase-store

Resources:
  PurchaseProcessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: 
            Service: lambda.amazonaws.com
          Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
      - PolicyName: S3Policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - 's3:PutObject'
            - 'S3:DeleteObject'
            Resource: !Sub "arn:aws:s3:::${BucketName}/*"

  PurchaseProcess:
    Type: AWS::Lambda::Function
    Properties:
      Description: Function that is called after file is written in S3 bucket.
      Handler: purchase_process.handler
      Runtime: nodejs12.x
      Role: !GetAtt PurchaseProcessRole.Arn
      Code: .
    
  PurchaseDataInput:
    Type: AWS::Lambda::Function
    Properties:
      Description: Function that takes in the customer info and writes into S3 bucket.
      Handler: purchase_input.handler
      Runtime: nodejs12.x
      Role: !GetAtt PurchaseProcessRole.Arn
      Code: .
      Environment:
        Variables:
          BucketName:
            Ref: BucketName

  Bucket:
    Type: AWS::S3::Bucket
    DependsOn: BucketPermission
    Properties:
      BucketName: !Ref BucketName
      NotificationConfiguration:
        LambdaConfigurations:
        - Event: 's3:ObjectCreated:*'
          Function: !GetAtt PurchaseProcess.Arn

  BucketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref PurchaseProcess
      Principal: s3.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"
      SourceArn: !Sub "arn:aws:s3:::${BucketName}"